# Artificial Neural Network

BUILDING AND ARTIFICIAL BRAIN

### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.17.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset=pd.read_csv('PCOS.csv')
X=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
print(X)

[[26 90 'Yes' 'Yes' 'Yes' 1.99 12.19 19.23]
 [24 45 'Yes' 'Yes' nan 1.06 14.57 14.36]
 [24 60 'Yes' 'Yes' nan 1.56 9.0 12.4]
 [24 90 'Yes' 'Yes' nan 1.17 11.99 16.2]
 [20 90 'Yes' 'Yes' nan 1.3 14.42 19.94]
 [20 45 'Yes' 'Yes' nan 4.15 8.3 19.41]
 [28 90 'Yes' 'Yes' 'Yes' 3.06 12.42 11.67]
 [34 90 'Yes' 'Yes' 'Yes' 3.18 8.75 17.46]
 [21 60 'Yes' 'Yes' nan 0.95 9.45 15.58]
 [32 60 'Yes' 'Yes' 'Yes' 1.78 10.64 11.77]
 [26 60 'Yes' 'Yes' 'Yes' 0.8 11.46 16.74]
 [27 45 'Yes' 'Yes' 'Yes' 4.91 12.21 16.94]
 [29 60 'Yes' 'Yes' 'Yes' 1.05 13.67 11.15]
 [19 90 'Yes' 'Yes' nan 1.62 12.99 19.39]
 [32 90 'Yes' 'Yes' 'Yes' 4.52 8.63 18.68]
 [34 90 'Yes' 'Yes' 'Yes' 1.75 9.32 17.75]
 [23 90 'Yes' 'Yes' nan 1.86 9.95 14.65]
 [29 60 'Yes' 'Yes' 'Yes' 3.28 10.01 14.53]
 [22 60 'Yes' 'Yes' nan 3.33 10.96 18.26]
 [28 45 'Yes' 'Yes' 'Yes' 2.29 11.3 12.04]
 [18 90 'Yes' 'Yes' nan 1.44 14.09 17.92]
 [23 60 'Yes' 'Yes' nan 1.41 11.9 12.45]
 [20 90 'Yes' 'Yes' nan 1.97 8.36 13.73]
 [18 60 'Yes' 'Yes' nan 1.85

In [ ]:
print(y)

['Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No']


### Encoding categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [ ]:
print(X)

[[26 90 1 'Yes' 'Yes' 1.99 12.19 19.23]
 [24 45 1 'Yes' nan 1.06 14.57 14.36]
 [24 60 1 'Yes' nan 1.56 9.0 12.4]
 [24 90 1 'Yes' nan 1.17 11.99 16.2]
 [20 90 1 'Yes' nan 1.3 14.42 19.94]
 [20 45 1 'Yes' nan 4.15 8.3 19.41]
 [28 90 1 'Yes' 'Yes' 3.06 12.42 11.67]
 [34 90 1 'Yes' 'Yes' 3.18 8.75 17.46]
 [21 60 1 'Yes' nan 0.95 9.45 15.58]
 [32 60 1 'Yes' 'Yes' 1.78 10.64 11.77]
 [26 60 1 'Yes' 'Yes' 0.8 11.46 16.74]
 [27 45 1 'Yes' 'Yes' 4.91 12.21 16.94]
 [29 60 1 'Yes' 'Yes' 1.05 13.67 11.15]
 [19 90 1 'Yes' nan 1.62 12.99 19.39]
 [32 90 1 'Yes' 'Yes' 4.52 8.63 18.68]
 [34 90 1 'Yes' 'Yes' 1.75 9.32 17.75]
 [23 90 1 'Yes' nan 1.86 9.95 14.65]
 [29 60 1 'Yes' 'Yes' 3.28 10.01 14.53]
 [22 60 1 'Yes' nan 3.33 10.96 18.26]
 [28 45 1 'Yes' 'Yes' 2.29 11.3 12.04]
 [18 90 1 'Yes' nan 1.44 14.09 17.92]
 [23 60 1 'Yes' nan 1.41 11.9 12.45]
 [20 90 1 'Yes' nan 1.97 8.36 13.73]
 [18 60 1 'Yes' nan 1.85 13.36 14.37]
 [35 90 1 'Yes' 'Yes' 2.62 8.76 10.16]
 [28 35 1 'No' 'No' 3.82 6.08 9.17]
 [18 35

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,3]=le.fit_transform(X[:,3])

In [ ]:
print(X)

[[26 90 1 1 'Yes' 1.99 12.19 19.23]
 [24 45 1 1 nan 1.06 14.57 14.36]
 [24 60 1 1 nan 1.56 9.0 12.4]
 [24 90 1 1 nan 1.17 11.99 16.2]
 [20 90 1 1 nan 1.3 14.42 19.94]
 [20 45 1 1 nan 4.15 8.3 19.41]
 [28 90 1 1 'Yes' 3.06 12.42 11.67]
 [34 90 1 1 'Yes' 3.18 8.75 17.46]
 [21 60 1 1 nan 0.95 9.45 15.58]
 [32 60 1 1 'Yes' 1.78 10.64 11.77]
 [26 60 1 1 'Yes' 0.8 11.46 16.74]
 [27 45 1 1 'Yes' 4.91 12.21 16.94]
 [29 60 1 1 'Yes' 1.05 13.67 11.15]
 [19 90 1 1 nan 1.62 12.99 19.39]
 [32 90 1 1 'Yes' 4.52 8.63 18.68]
 [34 90 1 1 'Yes' 1.75 9.32 17.75]
 [23 90 1 1 nan 1.86 9.95 14.65]
 [29 60 1 1 'Yes' 3.28 10.01 14.53]
 [22 60 1 1 nan 3.33 10.96 18.26]
 [28 45 1 1 'Yes' 2.29 11.3 12.04]
 [18 90 1 1 nan 1.44 14.09 17.92]
 [23 60 1 1 nan 1.41 11.9 12.45]
 [20 90 1 1 nan 1.97 8.36 13.73]
 [18 60 1 1 nan 1.85 13.36 14.37]
 [35 90 1 1 'Yes' 2.62 8.76 10.16]
 [28 35 0 0 'No' 3.82 6.08 9.17]
 [18 35 0 0 nan 0.6 7.18 7.65]
 [23 28 0 0 nan 2.79 6.98 5.3]
 [21 35 0 0 nan 1.87 6.5 6.25]
 [19 28 0 0 nan 3

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[4])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 0.0 26 90 1 1 1.99 12.19 19.23]
 [0.0 0.0 1.0 24 45 1 1 1.06 14.57 14.36]
 [0.0 0.0 1.0 24 60 1 1 1.56 9.0 12.4]
 [0.0 0.0 1.0 24 90 1 1 1.17 11.99 16.2]
 [0.0 0.0 1.0 20 90 1 1 1.3 14.42 19.94]
 [0.0 0.0 1.0 20 45 1 1 4.15 8.3 19.41]
 [0.0 1.0 0.0 28 90 1 1 3.06 12.42 11.67]
 [0.0 1.0 0.0 34 90 1 1 3.18 8.75 17.46]
 [0.0 0.0 1.0 21 60 1 1 0.95 9.45 15.58]
 [0.0 1.0 0.0 32 60 1 1 1.78 10.64 11.77]
 [0.0 1.0 0.0 26 60 1 1 0.8 11.46 16.74]
 [0.0 1.0 0.0 27 45 1 1 4.91 12.21 16.94]
 [0.0 1.0 0.0 29 60 1 1 1.05 13.67 11.15]
 [0.0 0.0 1.0 19 90 1 1 1.62 12.99 19.39]
 [0.0 1.0 0.0 32 90 1 1 4.52 8.63 18.68]
 [0.0 1.0 0.0 34 90 1 1 1.75 9.32 17.75]
 [0.0 0.0 1.0 23 90 1 1 1.86 9.95 14.65]
 [0.0 1.0 0.0 29 60 1 1 3.28 10.01 14.53]
 [0.0 0.0 1.0 22 60 1 1 3.33 10.96 18.26]
 [0.0 1.0 0.0 28 45 1 1 2.29 11.3 12.04]
 [0.0 0.0 1.0 18 90 1 1 1.44 14.09 17.92]
 [0.0 0.0 1.0 23 60 1 1 1.41 11.9 12.45]
 [0.0 0.0 1.0 20 90 1 1 1.97 8.36 13.73]
 [0.0 0.0 1.0 18 60 1 1 1.85 13.36 14.37]
 [0.0 1.

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
print(X_train)

[[1.0 0.0 0.0 25 30 0 0 3.89 7.04 9.75]
 [0.0 0.0 1.0 19 35 0 0 3.05 3.18 5.96]
 [0.0 0.0 1.0 18 35 0 0 0.6 7.18 7.65]
 [1.0 0.0 0.0 34 28 0 0 0.65 7.71 9.93]
 [0.0 0.0 1.0 22 60 1 1 3.33 10.96 18.26]
 [0.0 1.0 0.0 34 90 1 1 3.18 8.75 17.46]
 [0.0 1.0 0.0 32 90 1 1 4.52 8.63 18.68]
 [0.0 1.0 0.0 31 28 0 0 2.17 7.68 9.11]
 [1.0 0.0 0.0 29 35 0 0 4.2 6.43 6.85]
 [0.0 0.0 1.0 19 28 0 0 3.54 4.76 6.1]
 [0.0 1.0 0.0 34 90 1 1 1.75 9.32 17.75]
 [0.0 1.0 0.0 30 30 0 0 0.52 6.54 6.49]
 [1.0 0.0 0.0 30 30 0 0 3.78 7.16 7.25]
 [0.0 0.0 1.0 23 90 1 1 1.86 9.95 14.65]
 [0.0 1.0 0.0 28 35 0 0 2.89 7.86 5.7]
 [0.0 0.0 1.0 18 90 1 1 1.44 14.09 17.92]
 [0.0 0.0 1.0 20 35 1 1 0.92 3.5 8.57]
 [0.0 0.0 1.0 21 60 1 1 0.95 9.45 15.58]
 [0.0 0.0 1.0 19 90 1 1 1.62 12.99 19.39]
 [1.0 0.0 0.0 28 35 0 0 3.82 6.08 9.17]
 [0.0 0.0 1.0 20 45 1 1 4.15 8.3 19.41]
 [0.0 1.0 0.0 29 60 1 1 3.28 10.01 14.53]
 [0.0 0.0 1.0 24 28 0 0 2.72 5.85 5.85]
 [0.0 1.0 0.0 26 35 0 0 1.57 7.26 6.12]
 [0.0 0.0 1.0 24 45 1 1 1.06 14.

In [ ]:
print(X_test)

[[0.0 0.0 1.0 21 35 0 0 1.87 6.5 6.25]
 [0.0 1.0 0.0 27 45 1 1 4.91 12.21 16.94]
 [0.0 1.0 0.0 26 60 1 1 0.8 11.46 16.74]
 [0.0 0.0 1.0 18 35 1 1 2.46 3.32 5.53]
 [0.0 0.0 1.0 24 60 1 1 1.56 9.0 12.4]
 [0.0 0.0 1.0 23 28 0 0 2.79 6.98 5.3]
 [1.0 0.0 0.0 35 28 0 0 4.14 5.41 5.3]
 [0.0 0.0 1.0 24 28 0 0 0.89 5.3 5.69]
 [0.0 0.0 1.0 20 90 1 1 1.97 8.36 13.73]
 [0.0 0.0 1.0 20 90 1 1 1.3 14.42 19.94]]


In [ ]:
print(y_train)

[0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1
 1 0 0]


In [ ]:
print(y_test)

[0 1 1 0 1 0 0 0 1 1]


### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

a variable from the sequential class models module of keras libraray tensor flow2 is called

In [ ]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

add is a function of dense class which is used to add layers at any point

units sepecifies the number of eurons in the hidden layers 6 will give proper accuracy

activation is the activation function used relu is rectifier function

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

Adam is a popular optimization algorithm that efficiently updates the model's weights during training. It combines the advantages of two other optimization algorithms: Momentum and RMSprop.

Binary crossentropy is a loss function used for binary classification problems. It measures the dissimilarity between the predicted probability and the true binary label (0 or 1).

Accuracy is a common metric used to evaluate the performance of a classification model. It measures the proportion of correct predictions.

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#for multiclass classification we can use cross-entropy as loss function

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6146 - loss: 0.6714
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6250 - loss: 0.6605  
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6625 - loss: 0.6485 
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6521 - loss: 0.6519 
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6479 - loss: 0.6517 
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7438 - loss: 0.6358 
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7438 - loss: 0.6214 
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7333 - loss: 0.6150 
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7229 - loss: 0.6181 
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7604 - loss: 0.6146 
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7771 - loss: 0.6087 
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7771 - lo

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [ ]:
print(ann.predict(sc.transform([[0.0, 1.0,0.0, 27,60, 1,1, 3.2, 10.5,15.8]]))>0.5)
#without>0.5 it predicts prob of customer leaving bank..
#with us putting that it tells wether he will leave or not

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[ True]]


### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step
[[0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[5 0]
 [0 5]]


1.0